language: objective-c
osx_image: xcode7.3
xcode_project: ABNSDemo.xcodeproj
xcode_scheme: ABNSDemo
xcode_sdk: iphonesimulator9.3
script: xcodebuild -project ABNSDemo.xcodeproj -scheme ABNSDemo -sdk iphonesimulator9.3 build test
